### ISSUE TITLE
Add way to modify leaderboards after they have been created.

### ISSUE THREAD

**Issue by f0lie** [jacksonet00/github-leaderboard#20]
Currently, you can't modify the leaderboard url, start, or end dates.

**Comment by awhigham9** [comment]
I will take this on. I can just build a new view with a change form.

**Comment by awhigham9** [comment]
Added modifications for all the listed attributes and the name attribute. When the repo_url is changed, all commits associated with that leaderboard is dumped and the user is warned that they should refresh the leaderboard.

Done
